# Generated by Django 6.0.5 on 2026-05-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField(default=1)),
                ('fullness', models.PositiveIntegerField(default=40)),
                ('happiness', models.PositiveIntegerField(default=40)),
                ('is_sleeping', models.BooleanField(default=False)),
            ],
        ),
    ]
